### ISSUE TITLE
NixOS brand in 14.11

### ISSUE THREAD

**Issue by lucabrunox** [NixOS/nixos-artwork#1]
I aim for something very simple, without over-extending.
- A kde wallpaper, also for the installer
- A gnome wallpaper, I've done it already here http://oi59.tinypic.com/ekez5w.jpg
- A grub background

Additional wallpapers for display managers and other desktop managers are of course welcome.

**Comment by samueldr** [comment]
I believe this has all been handled since.

If something need to be handled, branding-wise, please open a new issue!
