### ISSUE TITLE
Logo for NixOS 23.11 Tapir

### ISSUE THREAD

**Issue by figsoda** [NixOS/nixos-artwork#104]
Hi everyone! I am the primary release manager for NixOS 23.11.

The next NixOS release is planned for the end of November 2023, you can see the full schedule [here](https://github.com/NixOS/nixpkgs/issues/258640).

The animal for this release is a [tapir](https://en.wikipedia.org/wiki/Tapir).

cc @riotbib

**Comment by samueldr** [comment]
cc @mogorman too

**Comment by mweinelt** [comment]
And let's poke @rwxg as well!

**Comment by the-furry-hubofeverything** [comment]
Some work is being done in #105

**Comment by figsoda** [comment]
I talked to @RaitoBezarius (and @mclegrand), and the conclusion was that #106 should be good to go. If there are no objections in a few days, I will go ahead and merge #106 and use it as the logo for this release.

cc @riotbib @the-furry-hubofeverything

**Comment by the-furry-hubofeverything** [comment]
> I talked to @RaitoBezarius (and @mclegrand), and the conclusion was that #106 should be good to go. If there are no objections in a few days, I will go ahead and merge #106 and use it as the logo for this release.
> 
> cc @riotbib @the-furry-hubofeverything

Objection!

The license for the stock photo was... Questionable (see final comments in #106), so I made a version using a cc0 stock in #107

**Comment by the-furry-hubofeverything** [comment]
Yeah turns out that other stock photo in #107 was under Pexel's license too

There's no way to filter them by license on the pexel website

I'm going to try to work on a different one (while triple checking the license), but if anyone else has any alternatives then please feel free to submit

**Comment by the-furry-hubofeverything** [comment]
![tapir-comparision](https://github.com/NixOS/nixos-artwork/assets/53921912/a865199e-cb1a-44f0-864d-eddee1cafae4)

Left: #108
Right: #109

I don't want to deal with licensing stuff - so here's the two alts I drew up - I've never drawn a Tapir before

I'll make a stock image alt tomorrow, I found a stock using CC-BY 2.0 on wikimedia

**Comment by the-furry-hubofeverything** [comment]
![image](https://github.com/NixOS/nixos-artwork/assets/53921912/63ce2938-cfe7-4fb1-b909-b41bd9437791)

Just so we're keeping track of all the options, @riotbib did #110, with a picture taken by himself.

**Comment by the-furry-hubofeverything** [comment]
We can close this issue now yeah?
