### ISSUE TITLE
Branding issues: logo and font

### ISSUE THREAD

**Issue by cillianderoiste** [NixOS/nixos-artwork#12]
This is a follow up to the discussion on the mailing list: https://www.mail-archive.com/nix-dev@lists.science.uu.nl/msg16520.html

There are a number of versions of the logo floating around, and no font is used consistently for "NixOS".

@gfsmonk has proposed some alternatives: https://github.com/gfxmonk/nixos-logo-ideas/tree/master/exports

The main issue with the current logo is the colors (IMO). The standard version http://nixos.org/logo/nixos-logo-only-hires.png is mainly blue, with some red. This can either look like purple or blue depending on the monitor, or the printing process. To work around this, a people who have printed their own t-shirts/stickers/banners etc. have chosen alternative colors (generally blue, rather than purple). A number of people have also used a purely black logo on a white background, and a purely white logo on a black background.

A designer at FOSDEM (@plastelina) told me that it should be pretty easy to pick out suitable colors and ensure they are consistent on all media. I know she had some ideas for the logo too, but ran out of time to complete them. Perhaps she can help us out here, or we can get help from some others at @opensourcedesign.

The initial font used for the NixOS logo was Myriad Web Pro, which is a proprietary font (used by Apple). Currently on nixos.org Liberation Sans is used, which is pretty generic. It would be great to adopt a Free font which is distinctive and suitable for the project.

It would be great to solve these issues (perhaps by choosing one of @gfxmonk's designs + a font), and it would make it easier for people to design consistently branded NixOS swag \o/

**Comment by yoroy** [comment]
Those explorations look great already. For making a final choice, you might want to consider:

How recognizable the lambda shape should be.
- the 'shape' variants don't work that well from that perspective
- The versions with one or multiple differently colored elements put more emphasis on the individual lambda element

Do you want the overall shape to be more solid or be more dynamic
- The hexagon outline makes things a bit more solid, also more snow flake like
- The cicle outline makes it a bit more dynamic overall

As a personal opinion, the 'hex, feature' version is the most expressive version with a strong character. I like the one accented element and the hex outline enforces the overall idea of the interlocking elements.

For the print variations, I would never put the name inside the logo element. It makes the text too small, the logo too big resulting in an imbalanced overall appearance.

For the typeface, could do worse than Fira: https://mozilla.github.io/Fira/

good luck!

**Comment by lethalman** [comment]
Closing as nixos now has a new logo.
