### ISSUE TITLE
NixOS artwork

### ISSUE THREAD

**Issue by Mathnerd314** [NixOS/nixos-artwork#13]
I found this amazing design on [Twitter](https://twitter.com/goodwillbits/status/568682428346155008):
![NixOS shirt design?](https://pbs.twimg.com/media/B-Rdp7gCcAEiZBM.png)

I think it should be in here.

cc @domenkozar

**Comment by lethalman** [comment]
Sure, whatelse should be in this repo if not this kind of artwork ;) It looks great.

**Comment by domenkozar** [comment]
@goodwillbits

**Comment by samueldr** [comment]
(Now outdated)
