### ISSUE TITLE
Add repository guidelines

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixos-artwork#14]
I have some content that might fit this repository.
- Nix Stickers files (illustrator CS5 format, can be converted to svg but might lose some information in the process such as cut lines)
- A few wallpapers (I am not a graphist and made them quickly, so they are very simple with a relative quality)

Is it the place to share it?

It would be nice to have simple guidelines in the readme explaining:
- Accepted resource types(wallpaper, DM themes, ...)
- File format and other details that might important (image size for wallpapers)
- contributing rules

**Comment by ericsagnes** [comment]
ping @lethalman 
Is this repository not used anymore?

**Comment by lethalman** [comment]
Yes this repository is fine. Just most of nixers are not artworkers :)

**Comment by ericsagnes** [comment]
good! 
How should I submit content? is there any recommended way to structure a PR and some do/dont?

Would it be interesting to have Nix related stickers illustrator files in here? I have made some and if it can be useful for somebody I will be more than happy to share them.

**Comment by lethalman** [comment]
@ericsagnes there's no decided structure, so put them where you want under some folder or create some new folder.

**Comment by ericsagnes** [comment]
Thanks! I just added a PR (#15).

**Comment by samueldr** [comment]
The underlying issue has been addressed.

Closing as outdated. We may want better guidelines, but that is part of a broader issue that needs solving anyway.
