### ISSUE TITLE
New logo → finish migrating from the old logo

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixos-artwork#16]
The artwork should use new Logo. Then we should bump package in nixpkgs.

**Comment by copumpkin** [comment]
The nixos.org one.

**Comment by kamilchm** [comment]
Can I find it somewhere in vector format?

**Comment by copumpkin** [comment]
If you take the text out of https://nixos.org/logo/nixos-hex.svg that should do it. We should get those into this repo though.

**Comment by globin** [comment]
Fixed in #18

**Comment by samueldr** [comment]
Leftover sightings inside this repo:

 * [common](https://github.com/NixOS/nixos-artwork/tree/master/common) which holds an older 3D-rendered wallpaper and grub (1?) images.
 * [gnome/**/Gnome_Dark.png](https://github.com/NixOS/nixos-artwork/tree/master/gnome)
 * Presumably [grub-background/grub-1.xpm](https://github.com/NixOS/nixos-artwork/tree/master/grub-background)
 * [kde/share/wallpapers/nixos-stripes/nixos-stripes.png](https://github.com/NixOS/nixos-artwork/tree/master/kde/share/wallpapers/nixos-stripes)
 * [slim/themes](https://github.com/NixOS/nixos-artwork/tree/master/slim/themes)
 * [swag/flyers/happier-hacking](https://github.com/NixOS/nixos-artwork/tree/master/swag/flyers/happier-hacking)

Of those, the grub* stuff can probably be dropped (use in nixpkgs should be verified first).

#26 will provide new assets for more modern bootloaders (and isolinux too).

The SLIM one can probably easily be knocked down.

The DE wallpapers can probably be replaced by a choice from a [fair dice roll guaranteed to be random](https://xkcd.com/221/) from the wallpapers folder.

What's left are random miscellaneous things.

**Comment by samueldr** [comment]
@samueldr any updates on the sightings?

**Comment by samueldr** [comment]
> @samueldr any updates on the sightings? 🙃

Get off my back, it's only been a bit over five years and a half.

Working on it.
