### ISSUE TITLE
License / Attribution for existing artwork.

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-artwork#23]
Going forward, it would be best if every contribution is specifically licensed under a license, whichever it is. This issue lists license and attribution issues. This is only a partial duplicate of #17, #17 is where an actual license for the repository should be discussed.

The logo's license and attribution is known. [Nix-dev mailing list, Sun Oct 2 08:49:55 CEST 2016](https://nixos.org/nix-dev/2016-October/021876.html).

* * *

# Unknown original source

<details><summary>(removed)</summary>

### Gnome wallpaper

The wallpaper was first shared in issue #1.

The background used in the wallpaper seems to originate from a "common" wallpaper found on the web. I could not link it to an original FLOSS source. It is unknown if it is okay to re-distribute or remix.

</details>

* * *

# No specific license or attribution

Ideally, we'd need these authors to specify a license under which the artwork can be used, and hopefully re-mixed. The contributions *looked* original enough to not cast any doubt about who the authors were. It is assumed the contributor is thus the author.

## @cillianderoiste

  * No specific license, all rights reserved @cillianderoiste. PR #10
      * `swag/flyers/happier-hacking/flyer-multi.pdf`
      * `swag/flyers/happier-hacking/flyer-optimized.svg`
      * `swag/flyers/happier-hacking/Readme.md`

## @jagajaga

  * No specific license, all rights reserved @jagajaga. PR #2
      * `grub-background/grub-1.xpm`

## @robberer

  * No specific license, all rights reserved @robberer. PR #5
      * `common/wallpapers/nixos-border.png`
  * No specific license, all rights reserved @robberer. PR #4
      * `common/grub2-background/grub-nixos-1.png`
      * `common/grub2-background/grub-nixos-1.xcf`
      * `common/grub2-background/grub-nixos-2.png`
      * `common/grub2-background/grub-nixos-2.xcf`
      * `common/grub2-background/grub-nixos-3.png`
      * `common/grub2-background/grub-nixos-3.xcf`

* * *

# Known attribution / license

These files are not problematic with regards to the license or attribution.

<details>

## @jagajaga 

  * [Upstream](https://github.com/jagajaga/nixos-slim-theme), MIT.
      * `slim/themes/nixos-theme.tar.gz`

## @lethalman

  * No specified liense, upstream wallpaper is GPL, modification by @lethalman. Assumed to be GPL. Commit b1c912ad918c256c7ebf2f5c2960a66cbc58570a
      * [Original by ivan-cukic](https://ivan-cukic.deviantart.com/art/KDE-Stripes-175023606)
      * [Contributed to the KDE project](https://github.com/KDE/kde-workspace/commit/bbd0bc62c7cbb074783af01086602c4de03fe8ac) as [GPL](https://github.com/KDE/kde-workspace/blob/bbd0bc62c7cbb074783af01086602c4de03fe8ac/COPYING)
      * `kde/share/wallpapers/nixos-stripes/nixos-stripes.png`
      * `kde/share/wallpapers/nixos-stripes/nixos-stripes.xcf`

</details>

 * * *

# Specified (new) attributions

<details>

## @ericsagnes

  * cc0 PR #15 / PR #29
      * `wallpapers/nix-wallpaper-mosaic-blue.png`
      * `wallpapers/nix-wallpaper-simple-blue.png`
      * `wallpapers/nix-wallpaper-simple-dark-gray.png`
      * `wallpapers/nix-wallpaper-simple-light-gray.png`
      * `wallpapers/nix-wallpaper-simple-red.png`
      * `wallpapers/nix-wallpaper-stripes-logo.png`
      * `wallpapers/nix-wallpaper-stripes.png`

</details>

**Comment by samueldr** [comment]
It looks like I forgot the `logo.scad` file, well I almost did. I'm assuming it is replaced by @Profpatsch in #20. If @offlinehacker wants to specify a license, it would be great, allowing us to document the older file's license.

The same applies for the older logo, I haven't made any work into finding the author or the license.

**Comment by ericsagnes** [comment]
Sorry for the late reply, for #15 contents please set the license that fits the repo best. Public domain or any creative commons is fine.

**Comment by samueldr** [comment]
Don't worry for the late reply; you're the first one to reply! And thanks for the reply!

@ericsagnes do you still have the original sources hanging around? It's a long shot, but this would help reviewing the wallpapers and/or making new variations.

**Comment by Ninlives** [comment]
Hi, according to https://github.com/NixOS/nixos-artwork/blob/master/CONTRIBUTORS.md#mogorman the logo for release 17.09 and 18.03 is under cc0, what about the following releases?y

**Comment by samueldr** [comment]
turns out this was already all handled in CONTRIBUTORS.md.
