### ISSUE TITLE
20.03 logo

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixos-artwork#48]
I'm noticing in the 19.09 release there's artwork for the news item https://github.com/NixOS/nixos-homepage/commit/a5626c71c03a2dd69086564e56f1a230a2bb177a#diff-9cdc6434d3e4fd93a6e5bb0a531a7c71. I don't think we have this :frowning: 

cc @samueldr @edolstra

**Comment by worldofpeace** [comment]
also cc @mogorman

**Comment by mogorman** [comment]
https://github.com/NixOS/nixos-artwork/pull/49
