### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by Th0rgal** [NixOS/nixos-artwork#50]
Hey there,

I had some free time today so I decided to redesign the logo, what are your thoughts?

Example propaganda image:
![Imgur](https://i.imgur.com/VrBIygH.png)

Logo (png):
![Imgur](https://i.imgur.com/6qFClA1.png)

Banner (for github readme):
![Imgur](https://i.imgur.com/y3YdnbH.png)

This is a vector (svg) so you can scale it at any size. You are free to do whatever you want with it (if you don't think it is too ugly haha), that's a gift for this awesome OS that I'm using everyday!

edit: [svg download link](https://files.artturin.com/files/nixoscolorful.svg) hosted by @Leo-Lahti

**Comment by hugolgst** [comment]
That's awesome! 
Totally up for it!

**Comment by ryantm** [comment]
I like the current one too, because the bluer tones invoke the frozen/snowflake theme more.

**Comment by Th0rgal** [comment]
I can try to use bluer tones if you want

**Comment by grahamc** [comment]
I like the re-imagining of the logo, in particular I like the blue pink and white going on. That said, I don't think updating the logo is on the table right now :)

**Comment by Th0rgal** [comment]
> I like the re-imagining of the logo, in particular I like the blue pink and white going on. That said, I don't think updating the logo is on the table right now :)

Thank you ! <3
I didn't create it with the intention of replacing the current logo haha. I'ld love to see people use it in wallpapers for example tho!

**Comment by mogorman** [comment]
Not a fan of it over the current version we have, but i do think it would make a great addition to the artwork in general.

**Comment by btwiusegentoo** [comment]
Thanks for great logo! Maybe I will use on my personally wallpaper combined with colorscheme background.
I couldn't find any wallpaper that I really like combined with that colorscheme.

**Comment by btwiusegentoo** [comment]
I didn't like the shadows, but I really liked the pink part!
so I got inspiration from this and made personally wallpaper with palenight colorscheme. thanks.

**Comment by Th0rgal** [comment]
> I didn't like the shadows, but I really liked the pink part!
> so I got inspiration from this and made personally wallpaper with palenight colorscheme. thanks.

Awesome, where can we see it?

**Comment by btwiusegentoo** [comment]
> > I didn't like the shadows, but I really liked the pink part!
> > so I got inspiration from this and made personally wallpaper with palenight colorscheme. thanks.
> 
> Awesome, where can we see it?

You can see on my nixconfig repo. wallpaper.png on root.
I'm not designer or anything so I just used fill tool on gimp to edit nixos logo color and I put it above palenight background though.

**Comment by Th0rgal** [comment]
Looks cool!

**Comment by grahamc** [comment]
I'm just closing this because it has created some confusion about what NixOS's official logo is. Thank you for submitting it!

**Comment by hugolgst** [comment]
Follow up for 20.09:

## r20.09 logo with dark background
<img width="645" alt="nixos-20 09" src="https://user-images.githubusercontent.com/15371828/111186705-90358980-85b3-11eb-8ffe-9f8f2219c635.png">

## r20.09 logo with transparent background
<img width="645" alt="nixos-20 09-transparent" src="https://user-images.githubusercontent.com/15371828/111186715-91ff4d00-85b3-11eb-9a6c-2543341da6f3.png">

## r20.09 logo with large text
<img width="1770" alt="nixos-20 09-large" src="https://user-images.githubusercontent.com/15371828/111186757-a04d6900-85b3-11eb-9ac4-efd355b725ee.png">

**Comment by hugolgst** [comment]
And for the OGs using unstable: 
<img width="645" alt="nixos-unstable" src="https://user-images.githubusercontent.com/15371828/111187201-14880c80-85b4-11eb-91a2-8a79669e86d1.png">

**Comment by davidak** [comment]
I really like these colors. It feels welcoming, special, professional. Thanks for sharing!

But i don't think we should change our current logo (that much) since we have build a brand over the years. If at all, changes should get applied in small iterations like professional brands do.

Examples: https://www.hongkiat.com/blog/logo-evolution/

**Comment by Th0rgal** [comment]
> I really like these colors. It feels welcoming, special, professional. Thanks for sharing!
> 
> But i don't think we should change our current logo (that much) since we have build a brand over the years. If at all, changes should get applied in small iterations like professional brands do.
> 
> Examples: https://www.hongkiat.com/blog/logo-evolution/

Thanks, I understand what you mean. If you want I could try to make one or two iterations between the current logo and this one so the transition would be better.

**Comment by davidak** [comment]
@Th0rgal yes, that would be nice. you can try to make the colors colder, so it looks more frozen :D

Then, i guess the forum is the best place to discuss it.

**Comment by illegitimate-egg** [comment]
What software was used to make this?

**Comment by mkukiro** [comment]
i wish this was the official logo it looks so much better ![](https://nukocities.neocities.org/nuko/react/cat91.gif)

**Comment by Th0rgal** [comment]
> What software was used to make this?

Hey, I used Adobe illustrator

**Comment by RobbieBuxton** [comment]
Is there anyway to re-open this issue? I do really think the Nix logo could do with a facelift.

**Comment by nyabinary** [comment]
> Is there anyway to re-open this issue? I do really think the Nix logo could do with a facelift.
> 
>     * The small gaps between the Lambda's really doesn't scale well when the logo is zoomed out.
> 
>     * I'm personally not a massive fan of the font they use for Nix either.
> 
> 
> Interestingly there currently is a slight shadow on each lambda but I think that should either be removed or made more prominent like in the suggested logo in this issue.

+1 on this.

**Comment by Malix-off** [comment]
The logo needs to be in vector (SVG) format, at bare minimum
Maybe reproducing the proposed logo from the current https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake-colours.svg icon would be the simplest way
