### ISSUE TITLE
Upload to wikimedia

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixos-artwork#51]
Can we upload your logo to wikimedia? @timbertson
I want to link it in the wikipedia article.

**Comment by grahamc** [comment]
fwiw, afaik, we have complete ownership over the logo and don't need to ask permission from @timbertson at this point.

**Comment by Mic92** [comment]
In the wikimedia form there are two options in the upload form. Either I claim that am the creator or I ask for permission via email with wikipedia in cc while uploading the image.

**Comment by timbertson** [comment]
Yes, I give permission

**Comment by Mic92** [comment]
Here we go: https://de.wikipedia.org/wiki/NixOS
