### ISSUE TITLE
Create a slide-show for the FOSDEM

### ISSUE THREAD

**Issue by nbp** [NixOS/nixos-artwork#6]
We should make a nice and entertaining slide-show to capture the attention of persons who are walking by a stand and are willing to stop watch some animated content promoting Nix / NixOS / NixOps.

**Comment by samueldr** [comment]
Closed as outdated. It would be something we need, still, but something that the marketing team (or a communications team) would be working together with the stakeholders about the vision of NixOS, and maybe the documentation authors.

In other words, not really branding guidelines and artwork anymore. (Though providing guidelines for branded slide-show and such, if needed can be requested in a fresh issue, with details!)
