### ISSUE TITLE
Request for all white NixOS logo lockup that works with GitHub dark mode

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixos-artwork#79]
Here is what the NixOS logo lockup looks like on the nixpkgs README with GitHub dark mode enabled:

![image](https://user-images.githubusercontent.com/4804/154552419-31c301c3-384f-40b0-bb91-9c49b9671397.png)

retrieved from https://github.com/nixos/nixpkgs

Would it be possible to make a logo lockup that can work with dark and light mode? Perhaps the letters can have a light gray stroke around them?

**Comment by ryantm** [comment]
Thanks for the reply!

GitHub supports [conditionally displaying the image](https://stackoverflow.com/questions/65413712/changing-readme-md-image-display-conditional-to-github-light-mode-dark-mode), so if a white version of the logo lockup were created, we could use that for darkmode.

**Comment by samueldr** [comment]
Oh, thanks for searching, and thanks for proving me wrong!

This could be used, we could provide a pre-baked version of the white logo for use in READMEs and such then.
