### ISSUE TITLE
Logo for the 22.11 Release

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixos-artwork#90]
The next NixOS release is planned for the end of November 2022.

The animal this time is supposed to be a raccoon.

@mogorman Would you be up for that?

**Comment by ardek66** [comment]
![nixos](https://user-images.githubusercontent.com/30049821/197045414-07feb32b-7d38-4ed4-85e4-608396a29d50.png)

**Comment by ardek66** [comment]
Alternative no. 2
![nixos2](https://user-images.githubusercontent.com/30049821/197253344-ceb8b686-aeef-4b9d-bdc2-4108e754e018.png)

**Comment by ardek66** [comment]
Alternative no 2.
![nixos21](https://user-images.githubusercontent.com/30049821/197253555-2c99c368-70ee-4174-a091-f214bf18e5ac.png)

**Comment by rwxg** [comment]
![Raccoons_Nix_01](https://user-images.githubusercontent.com/60877150/197892481-4ae861b5-074f-4330-a2ac-1ed6e435da33.png)

**Comment by rwxg** [comment]
Another one.
![Raccoons_Nix_01](https://user-images.githubusercontent.com/60877150/197996863-c4586bd0-4c07-4f08-b04e-692845a52c6c.png)
I realised that I borked the colour profile during the previous export. That should be fixed now.

**Comment by mogorman** [comment]
wow lots of good ones

**Comment by mweinelt** [comment]
Thanks everyone for contributing your creativity as well as time and energy!

I'm going to go with @rwxg's second proposal, PRed in #92, which resonates quite alot with me!
